### ISSUE TITLE
Code produces no output in Firefox but does in Chrome

### ISSUE THREAD

**Issue by amieres** [fsbolero/TryFSharpOnWasm#2]
The following code:

```
printfn "Hello!"
let rec listdir dir = 
    printfn "Dir: %s" dir
    for subdir in System.IO.Directory.EnumerateDirectories dir do
        printfn "SubDir: %s" subdir
    for file in System.IO.Directory.GetFiles(dir, "*") do
        printfn "File: %s" file
    for subdir in System.IO.Directory.EnumerateDirectories dir do
        listdir subdir

listdir "/"
```
 runs ok in Chrome but it produces no program output in FireFox or Edge.

EDIT:

Upon further check I found out that the output is produced but the pane does not show.

**Comment by Tarmil** [comment]
Right, there's a layout problem if the output is too large which hides the output panel. I'm looking into it.
