### ISSUE TITLE
Cannot switch the sample

### ISSUE THREAD

**Issue by wrometr** [fsbolero/TryFSharpOnWasm#6]
When I try to switch the sample, getting the html page  instead of the sample fs code, as a result other windows are broken to ("Compilation failed.
(4,23)-(4,25) Identifiers followed by '#' are reserved for future use")

![image](https://user-images.githubusercontent.com/48013055/59164184-159c2800-8b0a-11e9-81e0-61d205f9fa03.png)

I just downloaded and run the code, it is something related to the fact, that I have everything new from Blazor page?

**Comment by Tarmil** [comment]
I'm guessing you started the client project, rather than the server project, so it doesn't find the server files and returns the index instead. You need to set WebFsc.Server as the startup project.

I'm going to push a commit that makes that the default.
